spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
         - CustomTokenRelay=
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/banking-core/**
          filters:
            - StripPrefix=1
        - id: mvps-api
          uri: lb://mvps-api
          predicates:
            - Path=/mvps-api/**
          filters:
            - StripPrefix=1
        - id: core-transfer-service
          uri: lb://core-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: utility-service
          uri: lb://utility-service
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1
        - id: route1
          uri: http://localhost:8091/
          predicates:
            - Path=/resource1/**
          filters:
            - SetPath=/resourceserver01/
        - id: route2
          uri: http://localhost:8092/
          predicates:
            - Path=/resource2/**
          filters:
            - SetPath=/resourceserver02/
        - id: route3
          uri: http://localhost:8093/{segment}
          predicates:
            - Path=/resource3/{segment}
          filters:
            - SetPath=/resourceserver03/{segment}
        - id: mvps-ui
          uri: http://localhost:4200/
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8082/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
info:
  app:
    name: ${spring.application.name}

